version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/home/node/customer-crud
    networks:
      - app-network

networks:
  app-network:
    driver: bridge